import type { Sym } from '../../data/types.ts'

// How much an ability helps a playthrough, 0-1. Hand-curated: ability effects are too varied to read from
// descriptions. Unlisted abilities count as DEFAULT_ABILITY; hindering ones (Truant, Slow Start) are handled
// separately by hinderedByAbility.
export const DEFAULT_ABILITY = 0.1

export const ABILITY_VALUE: Record<Sym, number> = {
  // Doubles damage or snowballs every turn
  HUGEPOWER: 1, PUREPOWER: 1, SPEEDBOOST: 1, PROTEAN: 0.9, PARENTALBOND: 1, WONDERGUARD: 0.6,
  ADAPTABILITY: 0.9, WATERBUBBLE: 0.9, BATTLEBOND: 0.9, CONTRARY: 0.85, SHADOWTAG: 0.5,
  // Big passive damage boosts
  AERILATE: 0.8, PIXILATE: 0.8, REFRIGERATE: 0.8, GALVANIZE: 0.8, DUSKILATE: 0.8, MOXIE: 0.8, BEASTBOOST: 0.8,
  SOULHEART: 0.7, SHEERFORCE: 0.7, TOUGHCLAWS: 0.6, TECHNICIAN: 0.6, SKILLLINK: 0.6, TINTEDLENS: 0.6,
  MEGALAUNCHER: 0.6, NOGUARD: 0.5, STRONGJAW: 0.5, IRONFIST: 0.5, RECKLESS: 0.5, GUTS: 0.5, SERENEGRACE: 0.5,
  STEELWORKER: 0.4, HUSTLE: 0.3, SOLARPOWER: 0.4, SANDFORCE: 0.4, TOXICBOOST: 0.4, FLAREBOOST: 0.4,
  NEUROFORCE: 0.6, LIQUIDVOICE: 0.4, ANALYTIC: 0.3, SNIPER: 0.3, SUPERLUCK: 0.2, STAKEOUT: 0.3, MOLDBREAKER: 0.4,
  TERAVOLT: 0.4, TURBOBLAZE: 0.4, SCRAPPY: 0.3, COMPOUNDEYES: 0.3, GALEWINGS: 0.5, PRANKSTER: 0.6, TRIAGE: 0.4,
  // Defensive or field control
  INTIMIDATE: 0.8, FURCOAT: 0.8, MULTISCALE: 0.7, SHADOWSHIELD: 0.7, MAGICGUARD: 0.7, DISGUISE: 0.7,
  FLUFFY: 0.6, POISONHEAL: 0.6, REGENERATOR: 0.5, LEVITATE: 0.5, THICKFAT: 0.5, FILTER: 0.5, SOLIDROCK: 0.5,
  PRISMARMOR: 0.5, UNAWARE: 0.5, MAGICBOUNCE: 0.5, SIMPLE: 0.5, DOWNLOAD: 0.5, MARVELSCALE: 0.4, STURDY: 0.3,
  WATERABSORB: 0.4, VOLTABSORB: 0.4, FLASHFIRE: 0.4, SAPSIPPER: 0.4, STORMDRAIN: 0.4, LIGHTNINGROD: 0.4,
  MOTORDRIVE: 0.4, DRYSKIN: 0.3, BULLETPROOF: 0.3, DAZZLING: 0.4, QUEENLYMAJESTY: 0.4, STAMINA: 0.4,
  WATERCOMPACTION: 0.4, FULLMETALBODY: 0.3, CLEARBODY: 0.2, ROUGHSKIN: 0.3, IRONBARBS: 0.3, NATURALCURE: 0.2,
  SHEDSKIN: 0.3, COMPETITIVE: 0.4, DEFIANT: 0.3, BERSERK: 0.4, POWERCONSTRUCT: 0.7, SCHOOLING: 0.6,
  STANCECHANGE: 0.6, SHIELDSDOWN: 0.4, ZENMODE: 0.3, UNBURDEN: 0.5, QUICKFEET: 0.3,
  // Weather and terrain setters, and abilities that need them
  DROUGHT: 0.8, DRIZZLE: 0.8, SANDSTREAM: 0.5, SNOWWARNING: 0.5, PRIMORDIALSEA: 1, DESOLATELAND: 1, DELTASTREAM: 0.8,
  ELECTRICSURGE: 0.6, PSYCHICSURGE: 0.6, GRASSYSURGE: 0.6, MISTYSURGE: 0.5,
  SWIFTSWIM: 0.5, CHLOROPHYLL: 0.5, SANDRUSH: 0.4, SLUSHRUSH: 0.4, SURGESURFER: 0.4,
  // Weak or situational
  BLAZE: 0.2, TORRENT: 0.2, OVERGROW: 0.2, SWARM: 0.2
}

export const abilityValue = (a: Sym): number => ABILITY_VALUE[a] ?? DEFAULT_ABILITY

// Abilities that make the user outspeed foes over a fight, with the speed multiplier they are worth
export const SPEED_ABILITY: Record<Sym, number> = { SPEEDBOOST: 1.5 }
